name: Lean build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Lean and Lake
      uses: leanprover/lean-action@v1
      with:
        auto-config: true
    - name: Update lake manifest
      run: lake update
    - name: Build project
      run: lake build
