name: Lean build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Lake & Lean
      uses: leanprover/lean-action@v1
      with:
        lean-version: nightly
    - name: Build project
      run: lake build
